# Generated by Django 5.2.8 on 2025-11-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='ID_Genero', primary_key=True, serialize=False)),
                ('genero', models.CharField(db_column='Genero', max_length=20)),
            ],
            options={
                'db_table': 'Genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='ID_Rol', primary_key=True, serialize=False)),
                ('rol', models.CharField(db_column='Rol', max_length=20)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRol',
            fields=[
                ('id_userrol', models.AutoField(db_column='ID_UserRol', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'UserRol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('apellido1', models.CharField(db_column='Apellido1', max_length=50)),
                ('apellido2', models.CharField(blank=True, db_column='Apellido2', max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='Fecha_Nacimiento', null=True)),
                ('correo', models.EmailField(db_column='Correo', max_length=50, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=200)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=20, null=True)),
                ('fecha_creacion', models.DateField(blank=True, db_column='FechaCreacion', null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, db_column='FechaActualizacion', null=True)),
                ('fecha_eliminacion', models.DateField(blank=True, db_column='FechaEliminacion', null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
    ]
