# Generated by Django 5.2.8 on 2025-11-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genero',
            table='genero',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='userrol',
            table='userrol',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
