# Generated by Django 5.2.8 on 2025-11-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id_cita', models.AutoField(db_column='ID_Cita', primary_key=True, serialize=False)),
                ('peso', models.FloatField(blank=True, db_column='Peso', null=True)),
                ('estatura', models.FloatField(blank=True, db_column='Estatura', null=True)),
                ('fecha_cita', models.DateField(blank=True, db_column='Fecha_Cita', null=True)),
                ('notas', models.CharField(blank=True, db_column='Notas', max_length=255, null=True)),
                ('alcohol', models.BooleanField(db_column='Alcohol', default=False)),
                ('drogas', models.BooleanField(db_column='Drogas', default=False)),
                ('actividad_fisica', models.BooleanField(db_column='Actividad_Fisica', default=False)),
                ('fumador', models.BooleanField(db_column='Fumador', default=False)),
                ('enfermedad_cardiovascular', models.FloatField(blank=True, db_column='EnfermedadCardiovascular', null=True)),
                ('fecha_creacion', models.DateField(blank=True, db_column='FechaCreacion', null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, db_column='FechaActualizacion', null=True)),
                ('fecha_eliminacion', models.DateField(blank=True, db_column='FechaEliminacion', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Cita_Medica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangoColesterol',
            fields=[
                ('id_rango_colesterol', models.AutoField(db_column='ID_RangoColesterol', primary_key=True, serialize=False)),
                ('codigo_rango_colesterol', models.IntegerField(blank=True, db_column='CodigoRangoColesterol', null=True)),
                ('min', models.FloatField(blank=True, db_column='Min', null=True)),
                ('max', models.FloatField(blank=True, db_column='Max', null=True)),
                ('version_modelo', models.CharField(blank=True, db_column='VersionModelo', max_length=10, null=True)),
            ],
            options={
                'db_table': 'RangoColesterol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangoGlucosa',
            fields=[
                ('id_rango_glucosa', models.AutoField(db_column='ID_RangoGlucosa', primary_key=True, serialize=False)),
                ('codigo_rango_glucosa', models.IntegerField(blank=True, db_column='CodigoRangoGlucosa', null=True)),
                ('min', models.FloatField(blank=True, db_column='Min', null=True)),
                ('max', models.FloatField(blank=True, db_column='Max', null=True)),
                ('version_modelo', models.CharField(blank=True, db_column='VersionModelo', max_length=10, null=True)),
            ],
            options={
                'db_table': 'RangoGlucosa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangoIMC',
            fields=[
                ('id_rango_imc', models.AutoField(db_column='ID_RangoIMC', primary_key=True, serialize=False)),
                ('codigo_rango_imc', models.IntegerField(blank=True, db_column='CodigoRangoIMC', null=True)),
                ('min', models.FloatField(blank=True, db_column='Min', null=True)),
                ('max', models.FloatField(blank=True, db_column='Max', null=True)),
                ('version_modelo', models.CharField(blank=True, db_column='VersionModelo', max_length=10, null=True)),
            ],
            options={
                'db_table': 'RangoIMC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangoPresionSanguinea',
            fields=[
                ('id_rango_presion_sanguinea', models.AutoField(db_column='ID_RangoPresionSanguinea', primary_key=True, serialize=False)),
                ('codigo_rango_colesterol', models.IntegerField(blank=True, db_column='CodigoRangoColesterol', null=True)),
                ('min', models.FloatField(blank=True, db_column='Min', null=True)),
                ('max', models.FloatField(blank=True, db_column='Max', null=True)),
                ('version_modelo', models.CharField(blank=True, db_column='VersionModelo', max_length=10, null=True)),
            ],
            options={
                'db_table': 'RangoPresionSanguinea',
                'managed': False,
            },
        ),
    ]
