# Generated by Django 5.2.8 on 2025-11-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='citamedica',
            table='cita_medica',
        ),
        migrations.AlterModelTable(
            name='rangocolesterol',
            table='rangocolesterol',
        ),
        migrations.AlterModelTable(
            name='rangoglucosa',
            table='rangoglucosa',
        ),
        migrations.AlterModelTable(
            name='rangoimc',
            table='rangoimc',
        ),
        migrations.AlterModelTable(
            name='rangopresionsanguinea',
            table='rangopresionsanguinea',
        ),
    ]
